/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import javax.swing.JFrame;
import Vue.FenRService;
import java.awt.Button;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;

/**
 *
 * @author clara
 */
public class FenetreRecherche extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FenetreRecherche
     */
    public FenetreRecherche() {
        super("Gestion informatique de votre centre hospitalier");
        initComponents();
        setLocationRelativeTo(null); //on centre la fenêtre
        setResizable(false); //On empêche le redimensionnement
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); //pour quitter lors du clic sur la croix
        setVisible(true);
        jRadioButtonSer.addActionListener(this);
        Retour.addActionListener(this);
        jRadioChambre.addActionListener(this);
        jRadioDoc.addActionListener(this);
        jRadioEmp.addActionListener(this);
        jRadioHosp.addActionListener(this);
        jRadioInf.addActionListener(this);
        jRadioMal.addActionListener(this);
        jRadioSoigne.addActionListener(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jRadioButtonSer = new javax.swing.JRadioButton();
        jRadioInf = new javax.swing.JRadioButton();
        jRadioDoc = new javax.swing.JRadioButton();
        jRadioMal = new javax.swing.JRadioButton();
        jRadioEmp = new javax.swing.JRadioButton();
        jRadioHosp = new javax.swing.JRadioButton();
        jRadioChambre = new javax.swing.JRadioButton();
        jRadioSoigne = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonSer.setText("Recherche de service (Nom du Service, Bâtiments, Directeurs)");

        jRadioInf.setText("Recherche d'infirmiers");
        jRadioInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioInfActionPerformed(evt);
            }
        });

        jRadioDoc.setText("Recherche de médecins");
        jRadioDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDocActionPerformed(evt);
            }
        });

        jRadioMal.setText("Recherche de patients");
        jRadioMal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMalActionPerformed(evt);
            }
        });

        jRadioEmp.setText("Recherche d'employés");
        jRadioEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEmpActionPerformed(evt);
            }
        });

        jRadioHosp.setText("Recherche d'hopistalisation");
        jRadioHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioHospActionPerformed(evt);
            }
        });

        jRadioChambre.setText("Recherche de chambres");
        jRadioChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioChambreActionPerformed(evt);
            }
        });

        jRadioSoigne.setText("Recherche de personnes ayant été soignées dans le passé");
        jRadioSoigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSoigneActionPerformed(evt);
            }
        });

        jLabel1.setText("Veuillez choisir la recherche que vous souhaitez effectuer:");

        Retour.setText("Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioEmp)
                    .addComponent(jRadioMal, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioSoigne)
                    .addComponent(jRadioButtonSer)
                    .addComponent(jRadioHosp)
                    .addComponent(jRadioDoc)
                    .addComponent(jRadioChambre)
                    .addComponent(jRadioInf))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(Retour)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioMal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonSer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioChambre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioDoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioInf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioHosp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioSoigne)
                .addGap(18, 18, 18)
                .addComponent(Retour)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMalActionPerformed
       Object source = evt.getSource();
       if(source == jRadioMal) {
       super.dispose(); 
       //FenRMalade fenMalade= new FenRMalade();  // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMalActionPerformed
    }
    
     /*private void jRadioButtonSerActionPerformed(java.awt.event.ActionEvent evt) {                                                
       
         if (jRadioButtonSer.isSelected())  {
         FenRService fen = new FenRService();}
    }  */  
    
    public void actionPerformed (ActionEvent e){


        if(jRadioButtonSer.isSelected()){
            FenRService fen = new FenRService();
            super.dispose(); 
        }
    
        else if (jRadioChambre.isSelected()){
            try {
                FenRChambre fen = new FenRChambre();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            super.dispose(); 
        }
        
        else if (jRadioDoc.isSelected()){
           
            
            try {
                FenRDoc fen = new FenRDoc();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
            else if (jRadioEmp.isSelected()){
           
            
            try {
                FenREmp fen = new FenREmp();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
         else if (jRadioHosp.isSelected()){
           
            
            try {
                FenRHosp fen = new FenRHosp();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
         else if (jRadioInf.isSelected()){
           
            
            try {
                FenRInf fen = new FenRInf();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
         else if (jRadioMal.isSelected()){
           
            
            try {
                FenRMalade fen = new FenRMalade();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
        else if (jRadioSoigne.isSelected()){
           
            
            try {
                FenRSoigne fen = new FenRSoigne();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FenetreRecherche.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            super.dispose(); 
        }
        
        
       if(e.getSource()==Retour){
           FenChoixModule fen = new FenChoixModule();
           super.dispose();
       }
    
    }
    
       
        
    /*public void actionPerformedSer(ActionEvent evt) {
        Object source = evt.getSource();
       if(source == jRadioButtonSer) {
       super.dispose(); 
        FenRService fen = new FenRService();
    }
    }*/
    
    
    private void jRadioEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEmpActionPerformed

    private void jRadioHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioHospActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioHospActionPerformed

    private void jRadioChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioChambreActionPerformed

    private void jRadioSoigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSoigneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSoigneActionPerformed

    private void jRadioDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioDocActionPerformed

    private void jRadioInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioInfActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButtonSer;
    private javax.swing.JRadioButton jRadioChambre;
    private javax.swing.JRadioButton jRadioDoc;
    private javax.swing.JRadioButton jRadioEmp;
    private javax.swing.JRadioButton jRadioHosp;
    private javax.swing.JRadioButton jRadioInf;
    private javax.swing.JRadioButton jRadioMal;
    private javax.swing.JRadioButton jRadioSoigne;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

   
}
